# Generated by Django 5.1.3 on 2024-12-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_updates',
            field=models.JSONField(default=list),
        ),
    ]
