# Generated by Django 5.1.3 on 2024-12-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_my_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='my_updates',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_updates',
            field=models.JSONField(default=dict),
        ),
    ]
