# Generated by Django 5.1.3 on 2024-12-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_customuser_my_updates_customuser_user_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_notifications',
            field=models.JSONField(default=list),
        ),
    ]
