# Generated by Django 5.1.3 on 2024-12-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_user_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_action',
            field=models.JSONField(default=str),
        ),
    ]
