# Generated by Django 5.1.3 on 2024-12-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customuser_last_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_action_timezone',
            field=models.JSONField(default=str),
        ),
    ]
