# Generated by Django 5.1.3 on 2024-12-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_last_action_timezone_customuser_last_action_datetime_utc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_action',
        ),
    ]
