# Generated by Django 5.1.3 on 2024-12-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_customuser_last_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCoinNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255)),
            ],
        ),
    ]
